/**
 * HTTP response status codes used across the application.
 *
 * @readonly
 * @enum {number}
 */
export const RESPONSE_CODES = Object.freeze({
  SUCCESS_CODE: 200,
  CREATED_CODE: 201,
  RESOURCE_MOVED_PERMANENTLY_CODE: 301,
  REDIRECTION_CODE: 302,
  BAD_REQUEST_CODE: 400,
  UNAUTHORIZED_ERROR_CODE: 401,
  FORBIDDEN_ERROR_CODE: 403,
  NOT_FOUND_ERROR_CODE: 404,
  ACCESS_ERROR_CODE: 405,
  CONFLICT_ERROR_CODE: 409,
  UNPROCESSABLE_ERROR_CODE: 422,
  RATE_LIMIT_ERROR_CODE: 429,
  INTERNAL_SERVER_ERROR_CODE: 500,
});