export const ROLES = {
  EMPLOYEE: 'employee',
  HR_MANAGER: 'hr_manager',
  HR_PAYROLL_USER: 'hr_payroll_user',
  HR_PAYROLL_MANAGER: 'hr_payroll_manager',
  ADMIN: 'admin'
};

export const HR_ALL = [ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_MANAGER, ROLES.HR_PAYROLL_USER];
export const PAYROLL_WRITE = [ROLES.ADMIN, ROLES.HR_PAYROLL_MANAGER];
export const PAYROLL_READ = [ROLES.ADMIN, ROLES.HR_PAYROLL_MANAGER, ROLES.HR_PAYROLL_USER];
export const PAY_RUN_WRITE = [ROLES.ADMIN, ROLES.HR_PAYROLL_MANAGER, ROLES.HR_PAYROLL_USER];
export const ALL_ROLES = [ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.EMPLOYEE];
export const ADMIN_ONLY = [ROLES.ADMIN];
